In [1]:
import pandas as pd

In [2]:
pd.read_parquet("/home/intern_fjq_2026/Projects/chinese-wwm-roberta/artifacts/gubapost_cls/per_file/gubapost_20260513.parquet")

,available_date,symbol,n_posts,sum_cls,sum_prob,sum_attn_01,sum_attn_02,sum_attn_03,sum_attn_04,sum_attn_05,sum_attn_06,sum_attn_07,sum_attn_08,sum_attn_09,sum_attn_10,sum_attn_11,sum_attn_12
0,2026-05-13,600734,93,"[2.9, 44.5, 27.45, -4.64, -34.94, -4.504, 3.97...",17.081665,"[17.94, -0.01782, 8.19, -19.42, -23.92, 10.664...","[2.203, -0.5625, -1.667, 2.012, 4.035, 0.2776,...","[2.938, -1.518, -2.814, 1.07, 2.834, 1.424, -0...","[-2.87, 0.858, -1.389, 1.241, 0.2244, 1.703, -...","[-1.149, -1.135, -1.491, -2.02, -1.8125, -2.09...","[-1.795, 1.559, 0.4194, -1.29, -0.05835, 0.265...","[-0.143, -0.2039, -0.646, -2.137, 0.646, 0.596...","[0.1176, -1.359, 2.598, -1.784, -1.296, -1.077...","[-0.1028, 1.926, 1.586, 3.688, 1.593, 0.286, 1...","[4.797, -3.1, -0.4407, -2.05, 1.574, 0.766, -1...","[-1.827, -2.383, -3.836, 2.205, 1.894, -1.464,...","[-1.516, -0.5806, 1.626, 1.864, 1.903, 0.866, ..."
1,2026-05-13,002129,182,"[-1.194, 123.8, 99.6, -3.842, -76.75, -16.16, ...",32.808472,"[35.0, -0.1368, 16.53, -37.22, -45.44, 20.22, ...","[5.273, -0.9966, -3.525, 3.963, 7.68, 0.6284, ...","[5.605, -2.92, -5.562, 2.092, 5.15, 2.943, -1....","[-5.332, 2.041, -2.387, 2.201, -0.071, 3.129, ...","[-2.203, -2.133, -2.994, -4.035, -3.51, -4.08,...","[-3.588, 3.059, 0.904, -2.316, -0.3494, 0.3828...","[-0.4102, -0.4, -1.281, -4.074, 0.9556, 1.293,...","[0.1665, -2.768, 4.98, -3.473, -2.695, -2.033,...","[-0.3884, 3.686, 3.162, 7.4, 3.121, 0.935, 3.4...","[9.14, -6.156, -0.181, -2.895, 3.31, 1.524, -2...","[-2.613, -5.355, -7.44, 3.926, 4.25, -2.984, 2...","[-2.703, -4.28, -1.917, 3.719, 2.646, 2.08, -7..."
2,2026-05-13,002007,2,"[-0.5835, 1.701, 0.329, -0.04153, -2.102, 0.12...",0.340332,"[0.379, 0.03836, 0.1757, -0.4355, -0.5464, 0.2...","[0.0737, 0.00138, -0.0439, 0.04266, 0.0848, 0....","[0.0634, -0.03415, -0.0601, 0.0185, 0.0456, 0....","[-0.05215, 0.01935, -0.01605, 0.01848, 0.01418...","[-0.03912, -0.01897, -0.0357, -0.05206, -0.038...","[-0.0386, 0.03745, 0.01255, -0.02626, -0.00461...","[0.0009103, -0.001834, -0.006, -0.0461, 0.0061...","[-0.0014715, -0.02614, 0.05652, -0.03568, -0.0...","[0.0001087, 0.04144, 0.03122, 0.0796, 0.02948,...","[0.11163, -0.0717, -0.004242, -0.04034, 0.0312...","[-0.03375, -0.05453, -0.0793, 0.05518, 0.04733...","[0.01512, 0.1881, 0.0675, -0.06506, 0.1121, 0...."
3,2026-05-13,603601,2,"[0.4778, 1.286, 0.87, 0.2812, 0.1545, 0.3953, ...",0.417236,"[0.3884, 0.05374, 0.1814, -0.3745, -0.51, 0.22...","[0.06616, -0.0261, -0.0556, 0.04437, 0.0896, 0...","[0.05862, -0.03256, -0.0671, 0.013, 0.0619, 0....","[-0.02934, 0.01883, -0.03775, 0.02095, -0.0122...","[-0.00721, -0.02122, -0.03766, -0.05307, -0.03...","[-0.03485, 0.02466, 0.001308, -0.02892, -0.002...","[0.00711, -0.005188, -0.011734, -0.05124, 0.01...","[0.002632, -0.02547, 0.0549, -0.03665, -0.0302...","[0.002905, 0.03738, 0.03256, 0.0822, 0.032, 0....","[0.0997, -0.0619, -0.01047, -0.03848, 0.03134,...","[-0.03522, -0.05164, -0.081, 0.05475, 0.0493, ...","[-0.0365, 0.11804, 0.154, 0.02116, -0.04254, 0..."
4,2026-05-13,600794,88,"[-4.34, 29.64, 15.914, 17.02, -44.97, -12.71, ...",16.534851,"[17.5, 0.6826, 7.977, -18.05, -22.84, 10.03, -...","[2.19, -0.5986, -1.817, 2.13, 3.465, 0.584, 3....","[2.496, -1.249, -2.564, 1.092, 2.531, 1.526, -...","[-2.482, 1.3, -1.43, 1.504, 0.1947, 1.509, -0....","[-0.814, -0.9873, -1.585, -1.984, -1.875, -1.9...","[-1.671, 1.601, 0.4275, -1.059, -0.138, 0.4114...","[-0.07605, -0.3, -0.7266, -2.064, 0.5386, 0.42...","[0.02437, -1.278, 2.41, -1.699, -1.253, -1.011...","[-0.0748, 1.823, 1.526, 3.564, 1.45, 0.327, 1....","[4.55, -2.771, -0.4102, -1.679, 1.553, 0.6914,...","[-1.73, -2.348, -3.818, 2.04, 2.148, -1.434, 1...","[1.567, -1.082, 1.051, 1.623, 3.152, 0.8906, -..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9893,2026-05-14,300864,13,"[0.718, 4.2, 3.76, 2.842, -5.45, -1.316, 0.105...",2.361145,"[2.254, -0.1199, 1.206, -2.586, -3.008, 1.416,...","[0.2467, -0.03653, -0.2476, 0.322, 0.551, 0.07...","[0.4204, -0.1754, -0.4072, 0.1266, 0.4434, 0.1...","[-0.4187, 0.1417, -0.0816, 0.1819, -0.0976, 0....","[-0.1367, -0.1366, -0.2094, -0.3066, -0.2727, ...","[-0.2495, 0.2534, 0.0676, -0.1636, -0.0245, 0....","[-0.00882, -0.02419, -0.08, -0.3054, 0.0717, 0...","[-0.00569, -0.1947, 0.3828, -0.2482, -0.1877, ...","[-0.01944, 0.2683, 0.2241, 0.5107, 0.2063, 0.0...","[0.66, -0.396, -0.02313, -0.2546, 0.243, 0.076...","[-0.2395, -0.3787, -0.591, 0.303, 0.2795, -0.2...","[0.1312, -0.764, 0.04767, -0.4995, 0.431, -0.0..."
9894,2026-05-14,688128,7,"[-0.5215, 0.845, 1.509, 0.964, -2.275, -1.3125...",1.266235,"[1.331, -0.03674, 0.69, -1.515, -1.796, 0.836,...","[0.1895, -0.06024, -0.0949, 0.1793, 0.2725, 0....","[0.2263, -0.10394, -0.2098, 0.0724, 0.214, 0.1...","[-0.2177, 0.08044, -0.1162, 0.10834, -0.02481,...","[-0.05008, -0.0724, -0.09424, -0.1566, -0.1353...","[-0.12366, 0.12103, 0.02007, -0.08856, -0.0053...","[-0.00554, -0.01895, -0.0496, -0.1599, 0.0414,...","[-0.005257, -0.08997, 0.1823, -0.1311, -0.1012...","[0.002632, 0.1467, 0.1184, 0.284, 0.1136, 0.01...","[0.3652, -0.2231, -0.03485, -0.1246, 0.1221, 0...","[-0.1327, -0.1836, -0.2947, 0.1818, 0.1573, -0...","[-0.06964, 0.02954, 0.467, 0.1032, 0.3335, 0.0..."
9895,2026-05-14,301251,74,"[-6.42, 28.62, 23.1, 1.63, -31.7, -9.414, 7.49...",12.746887,"[13.67, 0.11957, 7.01, -15.04, -18.66, 8.11, -...","[1.683, -0.6353, -1.481, 1.358, 2.834, 0.3916,...","[2.479, -1.335, -2.143, 0.962, 2.375, 1.224, -...","[-2.285, 1.174, -1.008, 0.829, 0.1565, 1.623, ...","[-0.9277, -0.8633, -1.091, -1.708, -1.463, -1....","[-1.446, 1.295, 0.4207, -0.906, -0.129, 0.2203...","[-0.10803, -0.176, -0.2776, -1.52, 0.407, 0.45...","[0.04892, -1.108, 2.082, -1.363, -0.9585, -0.9...","[-0.1032, 1.448, 1.278, 2.986, 1.151, 0.3005, ...","[3.693, -2.344, -0.2515, -1.395, 1.269, 0.5527...","[-1.439, -1.969, -3.244, 1.861, 1.587, -1.221,...","[0.8364, 0.253, 2.791, -1.771, 0.6377, -0.2385..."
9896,2026-05-14,600894,71,"[4.26, 38.03, 21.19, 12.13, -30.88, -1.106, -0...",11.710327,"[13.23, 0.0524, 6.754, -14.42, -18.2, 8.04, -1...","[1.499, -0.3157, -1.535, 1.406, 2.6, 0.3367, 3...","[2.254, -1.187, -2.072, 0.9517, 2.154, 1.077, ...","[-2.5, 0.976, -0.938, 1.1, -0.08185, 1.415, -0...","[-0.679, -0.881, -1.056, -1.483, -1.308, -1.62...","[-1.383, 1.289, 0.3955, -1.033, -0.1348, 0.162...","[-0.1959, -0.1476, -0.4956, -1.626, 0.4963, 0....","[0.05563, -0.932, 1.962, -1.362, -1.055, -0.79...","[-0.0984, 1.542, 1.214, 2.715, 1.147, 0.1757, ...","[3.54, -2.133, 0.0523, -1.328, 1.346, 0.3477, ...","[-1.371, -1.892, -3.102, 1.687, 1.467, -1.223,...","[1.204, -2.719, -0.1605, -1.112, 1.35, 1.408, ..."
9897,2026-05-14,688560,22,"[1.31, 12.93, 4.094, 1.828, -8.84, -2.242, 3.0...",3.711731,"[4.27, -0.319, 2.11, -4.484, -5.453, 2.37, -3....","[0.3997, -0.1449, -0.4285, 0.4492, 0.9263, 0.1...","[0.6836, -0.3596, -0.639, 0.2145, 0.643, 0.278...","[-0.793, 0.2341, -0.327, 0.3047, 0.002245, 0.4...","[-0.2385, -0.2559, -0.3364, -0.5044, -0.4453, ...","[-0.4216, 0.4258, 0.0973, -0.3542, -0.04492, 0...","[-0.0714, -0.0334, -0.1492, -0.5156, 0.1458, 0...","[0.002598, -0.3281, 0.618, -0.404, -0.3667, -0...","[-0.04367, 0.4558, 0.416, 0.849, 0.3503, 0.090...","[1.134, -0.695, -0.0763, -0.4062, 0.353, 0.153...","[-0.4314, -0.5767, -0.958, 0.5225, 0.4683, -0....","[0.4114, -0.2961, 0.267, 0.2161, 0.6562, 0.184..."

In [2]:
# pd.read_csv("/home/intern_fjq_2026/Projects/chinese-wwm-roberta/filtered_data/social_text_202403.csv.gz")

In [3]:
import pymysql

conn = pymysql.connect(
    host='10.80.139.20',
    user='chenrongjun',          
    password='40!VEz6QX',       
    database='datayes',
    charset='utf8',
)
cursor = conn.cursor()
cursor.execute('SELECT VERSION(), DATABASE(), CURRENT_USER()')
print('✅ 连接成功:', cursor.fetchone())

✅ 连接成功: ('8.0.30', 'datayes', 'chenrongjun@%')

In [49]:
comment_info = pd.read_sql("""
    SELECT TABLE_NAME, TABLE_COMMENT
    FROM information_schema.tables 
    WHERE table_schema = DATABASE()
      AND TABLE_COMMENT != ''
    ORDER BY TABLE_NAME
    LIMIT 250, 25
""", conn)

print("=== 有注释的表 ===")
if len(comment_info) > 0:
    print(comment_info.to_string(index=False))
else:
    print("(暂无)")

=== 有注释的表 ===
                   TABLE_NAME    TABLE_COMMENT
                md_trade_spec            特殊交易日
                md_trade_time             交易时间
                      md_type           行业分类标准
      mfirstday_after_holiday        节假日首日时间信息
                     mkt_ibor        银行间同业拆借利率
       network_factors_table1         网络因子数据表1
     new_fortune_analyst_info        新财富分析师信息表
             news_co_event_v2        新闻公司事件表新表
           news_company_event        新闻公司事件分类表
           news_company_score     新闻关联公司及情感得分表
       news_company_score_his    新闻关联公司情感历史存量表
       news_company_score_inc      新闻关联公司情感增量表
        news_company_score_zx 新闻关联公司及情感得分表中信定制
           news_content_flash           快讯新闻主表
         news_industry_detail            期货标签表
                news_keywords           新闻关键词表
           news_manager_score        新闻基金经理关联表
news_policy_classification_v1            政策分类表
              news_popularity          新闻热度信息表
          news_security_score          新闻证券关联表
          news_stock_index_v2        公司新闻指数统计表
                  news_tag_v1          新闻关联标签表
                news_tagbd_zx      新闻关联标签表中信定制
               oper_data_agri       经营-农林牧渔数据表
               oper_data_auto         经营-汽车数据表

/tmp/ipykernel_8503/4118803541.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  comment_info = pd.read_sql("""

In [50]:
import pandas as pd
D = 'news_company_event'
# 1. 先看表结构（字段名和数据类型）
schema = pd.read_sql(f"""
    SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_COMMENT
    FROM information_schema.columns 
    WHERE table_name = '{D}'
    ORDER BY ORDINAL_POSITION
""", conn)
print("=== 表结构 ===")
print(schema.to_string(index=False))

=== 表结构 ===
      COLUMN_NAME DATA_TYPE IS_NULLABLE    COLUMN_DEFAULT COLUMN_COMMENT
               ID    bigint          NO              None           自增ID
          NEWS_ID    bigint         YES              None           新闻ID
       COMPANY_ID    bigint         YES              None         公司内部ID
        EVENT_1ST   varchar         YES              None         一级事件类别
        EVENT_2ND   varchar         YES              None         二级事件类别
   EFFECTIVE_TIME  datetime         YES              None       新闻有效发布时间
      CREATE_TIME  datetime         YES              None           创建时间
      UPDATE_TIME  datetime         YES              None           更新时间
HERMES_CREATETIME timestamp         YES CURRENT_TIMESTAMP
HERMES_UPDATETIME timestamp         YES CURRENT_TIMESTAMP

/tmp/ipykernel_8503/3664487632.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  schema = pd.read_sql(f"""

In [51]:
# 2. 看前几行数据 + 总行数
count = pd.read_sql(f'SELECT COUNT(*) AS cnt FROM {D}', conn).iloc[0]['cnt']
print(f"\n=== 共 {count} 行 ===\n")

/tmp/ipykernel_8503/965494187.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  count = pd.read_sql(f'SELECT COUNT(*) AS cnt FROM {D}', conn).iloc[0]['cnt']

=== 共 66777064 行 ===

In [47]:
pd.read_sql(f'SELECT * FROM {D} LIMIT 20', conn)

/tmp/ipykernel_8503/2643961264.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(f'SELECT * FROM {D} LIMIT 20', conn)

,ID,ANNO_ID,S3_ADDRESS,FILE_NAME,FILE_TYPE,UPDATE_TIME
0,4426035,637f8c839a723736cb776330,/pipeline/report/hk_iis/attachment/HKEX-EPS_20...,HKEX-EPS_20221124_10516472_0.HTM,htm,2024-12-20 14:38:10
1,4426036,637f8c839a723736cb7763fe,/pipeline/report/hk_iis/attachment/HKEX-EPS_20...,HKEX-EPS_20221124_10516468_0.HTM,htm,2024-12-20 14:36:59
2,4426040,637f8c859a723736cb776a00,/pipeline/report/hk_iis/attachment/HKEX-EPS_20...,HKEX-EPS_20221124_10516471_0.HTM,htm,2024-12-20 14:36:51
3,4426041,637f8c859a723736cb776a00,/pipeline/report/hk_iis/attachment/HKEX-EPS_20...,HKEX-EPS_20221124_10516471_1.PDF,pdf,2024-12-20 14:36:51
4,4426042,637f8c859a723736cb776a72,/pipeline/report/hk_iis/attachment/HKEX-EPS_20...,HKEX-EPS_20221124_10516467_0.HTM,htm,2024-12-20 14:37:23
5,4426043,637f8c859a723736cb776a72,/pipeline/report/hk_iis/attachment/HKEX-EPS_20...,HKEX-EPS_20221124_10516467_1.PDF,pdf,2024-12-20 14:37:23
6,4429825,638624609a723736cb8571c5,/pipeline/report/hk_iis/attachment/HKEX-EPS_20...,HKEX-EPS_20221129_10520594_0.HTM,htm,2024-12-20 14:40:00
7,4429826,638624649a723736cb857eb1,/pipeline/report/hk_iis/attachment/HKEX-EPS_20...,HKEX-EPS_20221129_10520593_0.HTM,htm,2024-12-20 14:38:54
8,4429827,638624649a723736cb857eb1,/pipeline/report/hk_iis/attachment/HKEX-EPS_20...,HKEX-EPS_20221129_10520593_1.PDF,pdf,2024-12-20 14:38:54
9,4434929,6388ce079a723736cbdb36ba,/pipeline/report/hk_iis/attachment/HKEX-EPS_20...,HKEX-EPS_20221201_10524503_0.HTM,htm,2024-12-20 14:41:08
10,4434930,6388ce089a723736cbdb378b,/pipeline/report/hk_iis/attachment/HKEX-EPS_20...,HKEX-EPS_20221201_10524499_0.HTM,htm,2024-12-20 14:43:36
11,4434936,6388ce099a723736cbdb380f,/pipeline/report/hk_iis/attachment/HKEX-EPS_20...,HKEX-EPS_20221201_10524502_0.HTM,htm,2024-12-20 14:39:25
12,4434937,6388ce0c9a723736cbdb3d2d,/pipeline/report/hk_iis/attachment/HKEX-EPS_20...,HKEX-EPS_20221201_10524498_0.HTM,htm,2024-12-20 14:43:36
13,4434938,6388ce0c9a723736cbdb3d2d,/pipeline/report/hk_iis/attachment/HKEX-EPS_20...,HKEX-EPS_20221201_10524498_1.PDF,pdf,2024-12-20 14:43:36
14,4434939,6388ce0c9a723736cbdb3d2d,/pipeline/report/hk_iis/attachment/HKEX-EPS_20...,HKEX-EPS_20221201_10524498_2.PDF,pdf,2024-12-20 14:43:36
15,4434940,6388ce0c9a723736cbdb3d2d,/pipeline/report/hk_iis/attachment/HKEX-EPS_20...,HKEX-EPS_20221201_10524498_3.PDF,pdf,2024-12-20 14:43:36
16,4445438,639746b39a723736cbad31e1,/pipeline/report/hk_iis/attachment/HKEX-EPS_20...,HKEX-EPS_20221212_10538808_0.HTM,htm,2024-12-20 14:34:17
17,4445439,639746b39a723736cbad31e1,/pipeline/report/hk_iis/attachment/HKEX-EPS_20...,HKEX-EPS_20221212_10538808_1.PDF,pdf,2024-12-20 14:34:17
18,4445440,639746b39a723736cbad31e1,/pipeline/report/hk_iis/attachment/HKEX-EPS_20...,HKEX-EPS_20221212_10538808_2.PDF,pdf,2024-12-20 14:34:17
19,4445441,639746b39a723736cbad31e1,/pipeline/report/hk_iis/attachment/HKEX-EPS_20...,HKEX-EPS_20221212_10538808_3.PDF,pdf,2024-12-20 14:34:17

In [35]:
date_col = "EFFECTIVE_TIME"
time_range = pd.read_sql(f"""
    SELECT MIN({date_col}) AS min_date, MAX({date_col}) AS max_date
    FROM {D}
""", conn)
print(f"统计日期范围：{time_range['min_date'].values[0]} → {time_range['max_date'].values[0]}")
print(f"共跨越 {len(pd.date_range(time_range['min_date'].values[0], time_range['max_date'].values[0]))} 个交易日")

/tmp/ipykernel_8503/4012238519.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  time_range = pd.read_sql(f"""

DatabaseError: Execution failed on sql '
    SELECT MIN(EFFECTIVE_TIME) AS min_date, MAX(EFFECTIVE_TIME) AS max_date
    FROM eco_data_bmedicine
': (1054, "Unknown column 'EFFECTIVE_TIME' in 'field list'")

In [94]:
symbol_col = "TICKER_SYMBOL"
pd.read_sql(f"""
    SELECT 
        AVG(cnt) AS avg_symbols_per_day
    FROM (
        SELECT COUNT(DISTINCT {symbol_col}) AS cnt
        FROM {D}
        WHERE {symbol_col} NOT LIKE '8%'
          AND {symbol_col} NOT LIKE '9%'
        GROUP BY {date_col}
    ) subq
""", conn)

/tmp/ipykernel_11251/1156218629.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(f"""

   avg_symbols_per_day
0            4670.3838